language: python
sudo: false
branches:
  except:
    - gh-pages

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-tornado
    - python: 2.7
      env: TOXENV=py27-twisted
    - python: 2.7
      env: TOXENV=py27-coverage
    - python: 2.6
      env: TOXENV=py26-tornado
    - python: 2.6
      env: TOXENV=py26-twisted
    - python: pypy
      env: TOXENV=pypy-tornado

cache:
  - apt

addons:
  apt:
    packages:
      - libssl-dev

install:
  - pip install tox

script:
  - tox
